### ISSUE TITLE
Allow > 3 clusters to be created via UI

### ISSUE THREAD

**Issue by mdarby** [getcarina/getcarina.com#701] opened 2016-02-19 15:04 UTC
The UI doesn't support the creation of clusters > 3, but the carina cli works fine.

**Comment by mdarby** [comment] 2016-02-19 15:05
(from https://community.getcarina.com/t/capacity-requests/22/3)

**Comment by rgbkrk** [comment] 2016-02-19 15:21
:boom: @carolynvs we win!!! :boom:

**Comment by ktbartholomew** [comment] 2016-02-19 16:40
Duplicate of https://github.com/getcarina/getcarina.com/issues/665

**Closed by ktbartholomew** 2016-02-19 16:40 UTC
